baseURL: "https://xgknight.com"
languageCode: en-us # zh-cn
title: Sean's Note
theme: PaperMod
paginate: 10

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10 # 重量越轻，就越往前面排，“1”则是置顶
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 10
    - identifier: about
      name: About
      url: /about/
      weight: 10

outputs:
  home:
    - HTML
    - RSS
    - JSON 

#taxonomies:
#    category: categories
#    tag: tags
#    series: series

markup:
  highlight:
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    # noClasses: false
    style: monokai

params:
  ShowBreadCrumbs: true # 面包屑导航
  ShowReadingTime: true # 阅读时间
  ShowWordCounts: true
  ShowShareButtons: false # 分享按钮
  ShowCodeCopyButtons: true
  ShowPostNavLinks: true # 文章前后页按钮
  ShowLastMod: true #显示文章更新时间
  DateFormat: "2006-01-02"
  ShowToc: true 
  TocOpen: true # 默认展开

  comments: true
  utteranc:
    enable: true
    repo: "seanlook/sean-notes-comment"
    issueTerm: "pathname"
    theme: "github-light"

  assets:
    disableHLJS: true

  defaultTheme: auto  # defaultTheme: light or  dark

  homeInfoParams:
    Title: '学习、思考和思考的地方' # 主题
    Content: '写一些给自己看的内容，然后觉得做一个网站比较屌而已' # 描述

  socialIcons:
      - name: github
        url: "https://github.com/seanlook"
      - name: RSS
        url: "index.xml"

  fuseOpts:
      isCaseSensitive: false
      shouldSort: true
      location: 0
      distance: 1000
      threshold: 0.4
      minMatchCharLength: 0
      # limit: 10
      keys: ["title", "permalink", "summary", "content"]

  assets:
      favicon: "img/logo.gif"
      favicon16x16: "img/logo.gif"
      favicon32x32: "img/logo.gif"
      apple_touch_icon: "logo.gif"
      safari_pinned_tab: "logo.gif"


minify:
    disableXML: true
    # minifyOutput: true

permalinks:
  page:
    #2018: /:year/:month/:day/:slug/
    posts: /posts/:slugorfilename/
  section:
    posts: /posts/
    tutorials: /training/
#  term:
#    tags: /:slug/

hasCJKLanguage: true # 自动检测是否包含中文日文韩文,如果文章中使用了很多中文引号的话可以开启
enableInlineShortcodes: true
enableEmoji: true # 允许使用 Emoji 表情，建议 true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
googleAnalytics: G-LNQSQM2192
